version: '3'

services:
  conductor-server:
    image: conductoross/conductor-server:3.13.8
    container_name: conductor-server
    environment:
      - CONFIG_PROP=config.properties
    ports:
      - "8080:8080"
    networks:
      - conductor-net
    depends_on:
      - elasticsearch
      - dynomite

  conductor-ui:
    image: conductoross/conductor-ui:3.13.8
    container_name: conductor-ui
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    ports:
      - "5000:5000"
    networks:
      - conductor-net
    depends_on:
      - conductor-server

  dynomite:
    image: v1r3n/dynomite
    container_name: dynomite
    ports:
      - "8102:8102"
    networks:
      - conductor-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
    container_name: elasticsearch
    environment:
      - "transport.host=0.0.0.0"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - conductor-net

networks:
  conductor-net:
